version: "3.9"
services:
  pluralia-api:
    build: .
    container_name: pluralia-api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pluralia
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: pluralia-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pluralia
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
